# Generated by Django 3.0.2 on 2020-03-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200327_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repertorymusic',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
